/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Meee (https://sketchfab.com/Meee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-hologram-87072288fb234226b9a3f02ae674a310
title: Earth hologram
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={3.27}>
          <mesh geometry={nodes.TERRE1_0.geometry} material={materials['Material.005']} />
        </group>
        <group rotation={[0, 0, -3.01]} scale={0.97}>
          <mesh geometry={nodes.Sphere002_0.geometry} material={materials['Material.006']} />
        </group>
        <group scale={4.79}>
          <mesh geometry={nodes.Circle643_0.geometry} material={materials['Material.004']} />
        </group>
        <group scale={0.18}>
          <mesh
            name="Circle455_0"
            geometry={nodes.Circle455_0.geometry}
            material={materials['Material.007']}
            morphTargetDictionary={nodes.Circle455_0.morphTargetDictionary}
            morphTargetInfluences={nodes.Circle455_0.morphTargetInfluences}
          />
        </group>
        <group scale={6.13}>
          <group position={[1, 0, 0]} scale={0.06}>
            <mesh geometry={nodes.Icosphere002_0.geometry} material={materials['Material.008']} />
          </group>
          <mesh geometry={nodes.Circle_0.geometry} material={materials['Material.010']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
